name: vieu
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  camera: ^0.10.3
  path: ^1.8.3
  path_provider: ^2.1.1
  lottie: ^2.6.0
  file_picker: ^5.5.0
  flutter_tflite: ^1.0.1
  image: ^3.2.0
  sqflite: ^2.3.0
  intl: ^0.18.1
  image_painter: ^0.6.1
  tflite_flutter: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter  


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/
    - assets/images/
    - assets/models/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
